AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a Lambda function to fetch and queue WBTC engine events every minute.

Globals:
  Function:
    Timeout: 20

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3SQSFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 's3-object-lambda:*'
                Resource: '*'
              - Effect: Allow
                Action: 'sqs:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'logs:TagResource'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  WBTCEventsFetcher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-handler.handler
      Runtime: nodejs16.x
      CodeUri: ./deploy-package
      FunctionName: !Sub 'WBTCEventsFetcher${FunctionNameSuffix}'
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        EveryMinuteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          NEW_EVENTS_QUEUE_URL: !Ref NewEventsQueueUrl
          NEW_EVENTS_QUEUE_URL_DEMO: !Ref NewEventsQueueUrlDemo
          S3_LAST_BLOCK_KEY: !Ref S3LastBlockKey
          S3_DEPLOYMENT_ADDRESS_KEY: !Ref S3DeploymentAddressKey
          S3_DEPLOYMENT_ADDRESS_KEY_DEMO: !Ref S3DeploymentAddressKeyDemo
          EVENTS_FETCH_PAGE_SIZE: !Ref EventsFetchPageSize
          NEW_RELIC_API_KEY: !Ref NewRelicAPIKey
          S3_BUCKET: !Ref S3Bucket
          S3_BUCKET_DEMO: !Ref S3BucketDemo
          S3_BUCKET_CONFIG: !Ref S3BucketConfig
          ENVIRONMENT: !Ref Environment
          S3_TEST_FORK_KEY: !Ref S3TestForkKey
          S3_DEMO_FORK_KEY: !Ref S3DemoForkKey

Parameters:
  NewEventsQueueUrl:
    Type: String
    Description: SQS Queue URL

  NewEventsQueueUrlDemo:
    Type: String
    Description: SQS Queue URL DEMO

  S3LastBlockKey:
    Type: String
    Description: S3 Key for Last Block Number

  S3DeploymentAddressKey:
    Type: String
    Description: S3 Key for Deployment Address

  S3DeploymentAddressKeyDemo:
    Type: String
    Description: S3 Key for Deployment DEMO Address

  EventsFetchPageSize:
    Type: Number
    Default: 1000
    Description: Events Fetch Page Size

  NewRelicAPIKey:
    Type: String
    Description: New Relic License Key

  S3Bucket:
    Type: String
    Description: S3 Bucket Name

  S3BucketDemo:
    Type: String
    Description: S3 Bucket Name Demo enviroment

  S3BucketConfig:
    Type: String
    Description: S3 Bucket Config Name

  Environment:
    Type: String
    Description: Environment
    Default: 'local'

  S3TestForkKey:
    Type: String
    Description: S3 Key for test RPC URL

  S3DemoForkKey:
    Type: String
    Description: S3 Key for Demo env RPC URL

  FunctionNameSuffix:
    Type: String
    Description: Function Name Suffix
    Default: ''
