AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a Lambda function to fetch and queue WBTC engine events every minute.

Globals:
  Function:
    Timeout: 20

Resources:
  WBTCEventsFetcher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-handler.handler
      Runtime: nodejs16.x
      CodeUri: ./deploy-package
      FunctionName: !Sub 'WBTCEventsFetcher${FunctionNameSuffix}'
      Events:
        EveryMinuteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          NEW_EVENTS_QUEUE_URL: !Ref NewEventsQueueUrl
          S3_LAST_BLOCK_KEY: !Ref S3LastBlockKey
          S3_DEPLOYMENT_ADDRESS_KEY: !Ref S3DeploymentAddressKey
          ALCHEMY_API_URL: !Ref AlchemyApiUrl
          INFURA_API_URL: !Ref InfuraApiUrl
          EVENTS_FETCH_PAGE_SIZE: !Ref EventsFetchPageSize
          NEW_RELIC_LICENSE_KEY: !Ref NewRelicLicenseKey
          NEW_RELIC_API_URL: !Ref NewRelicApiUrl
          S3_BUCKET: !Ref S3Bucket

Parameters:
  NewEventsQueueUrl:
    Type: String
    Description: SQS Queue URL

  S3LastBlockKey:
    Type: String
    Description: S3 Key for Last Block Number

  S3DeploymentAddressKey:
    Type: String
    Description: S3 Key for Deployment Address

  AlchemyApiUrl:
    Type: String
    Description: Alchemy API URL

  InfuraApiUrl:
    Type: String
    Description: Infura API URL

  EventsFetchPageSize:
    Type: Number
    Default: 1000
    Description: Events Fetch Page Size

  NewRelicLicenseKey:
    Type: String
    Description: New Relic License Key

  NewRelicApiUrl:
    Type: String
    Description: New Relic API URL

  S3Bucket:
    Type: String
    Description: S3 Bucket Name

  FunctionNameSuffix:
    Type: String
    Description: Function Name Suffix
    Default: ""
