AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a Lambda function to fetch and queue WBTC engine events every minute.

Globals:
  Function:
    Timeout: 20

Resources:
  WBTCEventsFetcher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-handler.handler
      Runtime: nodejs16.x
      CodeUri: ./deploy-package
      Events:
        EveryMinuteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Environment:
        Variables:
          NEW_EVENTS_QUEUE_URL: !Ref NewEventsQueueUrl
          S3_BUCKET: !Ref WbtcEventsS3Bucket
          S3_LAST_BLOCK_KEY: !Ref S3LastBlockKey
          S3_DEPLOYMENT_ADDRESS_KEY: !Ref S3DeploymentAddressKey
          ALCHEMY_API_URL: !Ref AlchemyApiUrl
          INFURA_API_URL: !Ref InfuraApiUrl
          EVENTS_FETCH_PAGE_SIZE: !Ref EventsFetchPageSize
          NEW_RELIC_LICENSE_KEY: !Ref NewRelicLicenseKey
          NEW_RELIC_API_URL: !Ref NewRelicApiUrl
          AWS_REGION: !Ref AwsRegion
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref WbtcEventsS3Bucket

  WbtcEventsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3Bucket

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WbtcEventsS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LambdaS3Access
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource: !Sub 'arn:aws:s3:::${WbtcEventsS3Bucket}/*'

Parameters:
  NewEventsQueueUrl:
    Type: String
    Description: SQS Queue URL

  S3Bucket:
    Type: String
    Description: S3 Bucket Name

  S3LastBlockKey:
    Type: String
    Description: S3 Key for Last Block Number

  S3DeploymentAddressKey:
    Type: String
    Description: S3 Key for Deployment Address

  AlchemyApiUrl:
    Type: String
    Description: Alchemy API URL

  InfuraApiUrl:
    Type: String
    Description: Infura API URL

  EventsFetchPageSize:
    Type: Number
    Default: 1000
    Description: Events Fetch Page Size

  NewRelicLicenseKey:
    Type: String
    Description: New Relic License Key

  NewRelicApiUrl:
    Type: String
    Description: New Relic API URL

  AwsRegion:
    Type: String
    Default: us-east-1
    Description: AWS Region
