/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ConvexPoolAdapter {
  export type RewardDataStruct = {
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type RewardDataStructOutput = [string, BigNumber] & {
    token: string;
    amount: BigNumber;
  };
}

export interface ConvexPoolAdapterInterface extends utils.Interface {
  functions: {
    "CONVEX_BOOSTER()": FunctionFragment;
    "CURVE_TOKEN()": FunctionFragment;
    "CVX()": FunctionFragment;
    "CVX_MAX_SUPPLY()": FunctionFragment;
    "ETH()": FunctionFragment;
    "WETH()": FunctionFragment;
    "claim()": FunctionFragment;
    "convexPid()": FunctionFragment;
    "convexRewardPool()": FunctionFragment;
    "curveLpToken()": FunctionFragment;
    "curvePool()": FunctionFragment;
    "deposit(uint256,uint256)": FunctionFragment;
    "healthFactor()": FunctionFragment;
    "indexUint()": FunctionFragment;
    "initialize(address,address,uint256,uint256,address,bool,bool,int128)": FunctionFragment;
    "isHealthy()": FunctionFragment;
    "lpBalance()": FunctionFragment;
    "multiPoolStrategy()": FunctionFragment;
    "rewardTokens(uint256)": FunctionFragment;
    "setHealthFactor(uint256)": FunctionFragment;
    "storedUnderlyingBalance()": FunctionFragment;
    "tokensLength()": FunctionFragment;
    "totalClaimable()": FunctionFragment;
    "underlyingBalance()": FunctionFragment;
    "underlyingToken()": FunctionFragment;
    "underlyingTokenPoolIndex()": FunctionFragment;
    "useEth()": FunctionFragment;
    "withdraw(uint256,uint256)": FunctionFragment;
    "zapper()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CONVEX_BOOSTER"
      | "CURVE_TOKEN"
      | "CVX"
      | "CVX_MAX_SUPPLY"
      | "ETH"
      | "WETH"
      | "claim"
      | "convexPid"
      | "convexRewardPool"
      | "curveLpToken"
      | "curvePool"
      | "deposit"
      | "healthFactor"
      | "indexUint"
      | "initialize"
      | "isHealthy"
      | "lpBalance"
      | "multiPoolStrategy"
      | "rewardTokens"
      | "setHealthFactor"
      | "storedUnderlyingBalance"
      | "tokensLength"
      | "totalClaimable"
      | "underlyingBalance"
      | "underlyingToken"
      | "underlyingTokenPoolIndex"
      | "useEth"
      | "withdraw"
      | "zapper"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CONVEX_BOOSTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CURVE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CVX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CVX_MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "convexPid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convexRewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "curveLpToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "curvePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "healthFactor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "indexUint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "isHealthy", values?: undefined): string;
  encodeFunctionData(functionFragment: "lpBalance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiPoolStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setHealthFactor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "storedUnderlyingBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingTokenPoolIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "useEth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "zapper", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CONVEX_BOOSTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CURVE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CVX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CVX_MAX_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "convexPid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convexRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "curveLpToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "curvePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "indexUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHealthy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiPoolStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedUnderlyingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingTokenPoolIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useEth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zapper", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ConvexPoolAdapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConvexPoolAdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CONVEX_BOOSTER(overrides?: CallOverrides): Promise<[string]>;

    CURVE_TOKEN(overrides?: CallOverrides): Promise<[string]>;

    CVX(overrides?: CallOverrides): Promise<[string]>;

    CVX_MAX_SUPPLY(overrides?: CallOverrides): Promise<[BigNumber]>;

    ETH(overrides?: CallOverrides): Promise<[string]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    convexPid(overrides?: CallOverrides): Promise<[BigNumber]>;

    convexRewardPool(overrides?: CallOverrides): Promise<[string]>;

    curveLpToken(overrides?: CallOverrides): Promise<[string]>;

    curvePool(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _minCurveLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    healthFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    indexUint(overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _curvePool: PromiseOrValue<string>,
      _multiPoolStrategy: PromiseOrValue<string>,
      _convexPid: PromiseOrValue<BigNumberish>,
      _tokensLength: PromiseOrValue<BigNumberish>,
      _zapper: PromiseOrValue<string>,
      _useEth: PromiseOrValue<boolean>,
      _indexUint: PromiseOrValue<boolean>,
      _underlyingTokenPoolIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isHealthy(overrides?: CallOverrides): Promise<[boolean]>;

    lpBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { lpBal: BigNumber }>;

    multiPoolStrategy(overrides?: CallOverrides): Promise<[string]>;

    rewardTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setHealthFactor(
      _newHealthFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    storedUnderlyingBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokensLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalClaimable(
      overrides?: CallOverrides
    ): Promise<[ConvexPoolAdapter.RewardDataStructOutput[]]>;

    underlyingBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { underlyingBal: BigNumber }>;

    underlyingToken(overrides?: CallOverrides): Promise<[string]>;

    underlyingTokenPoolIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    useEth(overrides?: CallOverrides): Promise<[boolean]>;

    withdraw(
      _amount: PromiseOrValue<BigNumberish>,
      _minReceiveAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    zapper(overrides?: CallOverrides): Promise<[string]>;
  };

  CONVEX_BOOSTER(overrides?: CallOverrides): Promise<string>;

  CURVE_TOKEN(overrides?: CallOverrides): Promise<string>;

  CVX(overrides?: CallOverrides): Promise<string>;

  CVX_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

  ETH(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  claim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  convexPid(overrides?: CallOverrides): Promise<BigNumber>;

  convexRewardPool(overrides?: CallOverrides): Promise<string>;

  curveLpToken(overrides?: CallOverrides): Promise<string>;

  curvePool(overrides?: CallOverrides): Promise<string>;

  deposit(
    _amount: PromiseOrValue<BigNumberish>,
    _minCurveLpAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  healthFactor(overrides?: CallOverrides): Promise<BigNumber>;

  indexUint(overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _curvePool: PromiseOrValue<string>,
    _multiPoolStrategy: PromiseOrValue<string>,
    _convexPid: PromiseOrValue<BigNumberish>,
    _tokensLength: PromiseOrValue<BigNumberish>,
    _zapper: PromiseOrValue<string>,
    _useEth: PromiseOrValue<boolean>,
    _indexUint: PromiseOrValue<boolean>,
    _underlyingTokenPoolIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isHealthy(overrides?: CallOverrides): Promise<boolean>;

  lpBalance(overrides?: CallOverrides): Promise<BigNumber>;

  multiPoolStrategy(overrides?: CallOverrides): Promise<string>;

  rewardTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  setHealthFactor(
    _newHealthFactor: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  storedUnderlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

  tokensLength(overrides?: CallOverrides): Promise<BigNumber>;

  totalClaimable(
    overrides?: CallOverrides
  ): Promise<ConvexPoolAdapter.RewardDataStructOutput[]>;

  underlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

  underlyingToken(overrides?: CallOverrides): Promise<string>;

  underlyingTokenPoolIndex(overrides?: CallOverrides): Promise<BigNumber>;

  useEth(overrides?: CallOverrides): Promise<boolean>;

  withdraw(
    _amount: PromiseOrValue<BigNumberish>,
    _minReceiveAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  zapper(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CONVEX_BOOSTER(overrides?: CallOverrides): Promise<string>;

    CURVE_TOKEN(overrides?: CallOverrides): Promise<string>;

    CVX(overrides?: CallOverrides): Promise<string>;

    CVX_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    claim(overrides?: CallOverrides): Promise<void>;

    convexPid(overrides?: CallOverrides): Promise<BigNumber>;

    convexRewardPool(overrides?: CallOverrides): Promise<string>;

    curveLpToken(overrides?: CallOverrides): Promise<string>;

    curvePool(overrides?: CallOverrides): Promise<string>;

    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _minCurveLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    healthFactor(overrides?: CallOverrides): Promise<BigNumber>;

    indexUint(overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _curvePool: PromiseOrValue<string>,
      _multiPoolStrategy: PromiseOrValue<string>,
      _convexPid: PromiseOrValue<BigNumberish>,
      _tokensLength: PromiseOrValue<BigNumberish>,
      _zapper: PromiseOrValue<string>,
      _useEth: PromiseOrValue<boolean>,
      _indexUint: PromiseOrValue<boolean>,
      _underlyingTokenPoolIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isHealthy(overrides?: CallOverrides): Promise<boolean>;

    lpBalance(overrides?: CallOverrides): Promise<BigNumber>;

    multiPoolStrategy(overrides?: CallOverrides): Promise<string>;

    rewardTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    setHealthFactor(
      _newHealthFactor: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    storedUnderlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

    tokensLength(overrides?: CallOverrides): Promise<BigNumber>;

    totalClaimable(
      overrides?: CallOverrides
    ): Promise<ConvexPoolAdapter.RewardDataStructOutput[]>;

    underlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingToken(overrides?: CallOverrides): Promise<string>;

    underlyingTokenPoolIndex(overrides?: CallOverrides): Promise<BigNumber>;

    useEth(overrides?: CallOverrides): Promise<boolean>;

    withdraw(
      _amount: PromiseOrValue<BigNumberish>,
      _minReceiveAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    zapper(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    CONVEX_BOOSTER(overrides?: CallOverrides): Promise<BigNumber>;

    CURVE_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    CVX(overrides?: CallOverrides): Promise<BigNumber>;

    CVX_MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    convexPid(overrides?: CallOverrides): Promise<BigNumber>;

    convexRewardPool(overrides?: CallOverrides): Promise<BigNumber>;

    curveLpToken(overrides?: CallOverrides): Promise<BigNumber>;

    curvePool(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _minCurveLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    healthFactor(overrides?: CallOverrides): Promise<BigNumber>;

    indexUint(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _curvePool: PromiseOrValue<string>,
      _multiPoolStrategy: PromiseOrValue<string>,
      _convexPid: PromiseOrValue<BigNumberish>,
      _tokensLength: PromiseOrValue<BigNumberish>,
      _zapper: PromiseOrValue<string>,
      _useEth: PromiseOrValue<boolean>,
      _indexUint: PromiseOrValue<boolean>,
      _underlyingTokenPoolIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isHealthy(overrides?: CallOverrides): Promise<BigNumber>;

    lpBalance(overrides?: CallOverrides): Promise<BigNumber>;

    multiPoolStrategy(overrides?: CallOverrides): Promise<BigNumber>;

    rewardTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setHealthFactor(
      _newHealthFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    storedUnderlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

    tokensLength(overrides?: CallOverrides): Promise<BigNumber>;

    totalClaimable(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingBalance(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingToken(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingTokenPoolIndex(overrides?: CallOverrides): Promise<BigNumber>;

    useEth(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _amount: PromiseOrValue<BigNumberish>,
      _minReceiveAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    zapper(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CONVEX_BOOSTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CURVE_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CVX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CVX_MAX_SUPPLY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    convexPid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    convexRewardPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    curveLpToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    curvePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _minCurveLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    healthFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    indexUint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _curvePool: PromiseOrValue<string>,
      _multiPoolStrategy: PromiseOrValue<string>,
      _convexPid: PromiseOrValue<BigNumberish>,
      _tokensLength: PromiseOrValue<BigNumberish>,
      _zapper: PromiseOrValue<string>,
      _useEth: PromiseOrValue<boolean>,
      _indexUint: PromiseOrValue<boolean>,
      _underlyingTokenPoolIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isHealthy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiPoolStrategy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rewardTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setHealthFactor(
      _newHealthFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    storedUnderlyingBalance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokensLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalClaimable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingTokenPoolIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    useEth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _amount: PromiseOrValue<BigNumberish>,
      _minReceiveAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    zapper(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
