name: Acceptance Stage

on:
    pull_request:
      branches:
        - main 

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  API_DEVOPS_EVENT_CATCHER: ${{ vars.API_DEVOPS_EVENT_CATCHER }}
  DEVOPS_EVENTS_SECRET_TOKEN: ${{ secrets.DEVOPS_EVENTS_SECRET_TOKEN }}

  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
  NEW_RELIC_API_URL: ${{ vars.NEW_RELIC_API_URL }}

  S3_BUCKET_CONFIG: ${{ secrets.S3_BUCKET_CONFIG }}
  S3_FORK_KEY: ${{ secrets.S3_FORK_KEY }}
  S3_DEPLOYMENT_ADDRESS_KEY: ${{ secrets.S3_DEPLOYMENT_ADDRESS_KEY }}

  NEW_EVENTS_QUEUE_URL: ${{ secrets.NEW_EVENTS_QUEUE_URL_DEMO }}
  
  PSP_ACCEPTANCE_TEST_NODE: ${{ vars.PSP_ACCEPTANCE_TEST_NODE }}
  PSP_STRATEGY_CONFIG_BUCKET: ${{ vars.PSP_STRATEGY_CONFIG_BUCKET }}
  PSP_STRATEGY_CONFIG_FILE: ${{ vars.PSP_STRATEGY_CONFIG_FILE }}
  
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

jobs:
    acceptance-tests:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4
              with:
               submodules: 'recursive'
               fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: yarn install

            - name: Run acceptance tests
              run: |
                yarn test:acceptance
      
            - name: Slack Notification
              if: always()
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      
