name: Deploy to AWS Lambda using SAM

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Remove development dependencies
        run: npm prune --production

      - name: Prepare deployment package
        run: |
          mkdir -p deploy-package
          cp -r ./dist/* ./deploy-package/
          cp -r ./node_modules ./deploy-package/

      - name: List contents of deploy-package directory
        run: ls -al ./deploy-package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install --user aws-sam-cli

      - name: Package the SAM application
        run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket aws-sam-eventsfetcher

      - name: Deploy the SAM application
        run: |
          sam deploy --template-file packaged.yaml --stack-name EventProcessorStack --capabilities CAPABILITY_IAM --parameter-overrides \
          ParameterKey=LeverageEngineAddress,ParameterValue="${{ secrets.LEVERAGE_ENGINE_ADDRESS }}" \
          ParameterKey=NewEventsQueueUrl,ParameterValue="${{ secrets.NEW_EVENTS_QUEUE_URL }}" \
          ParameterKey=S3Bucket,ParameterValue="${{ secrets.S3_BUCKET }}" \
          ParameterKey=S3Key,ParameterValue="${{ secrets.S3_KEY }}" \
          ParameterKey=AlchemyApiUrl,ParameterValue="${{ secrets.ALCHEMY_API_URL }}" \
          ParameterKey=InfuraApiUrl,ParameterValue="${{ secrets.INFURA_API_URL }}" \
          ParameterKey=EventsFetchPageSize,ParameterValue="${{ secrets.EVENTS_FETCH_PAGE_SIZE }}"

