name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create .env file
        run: |
          echo LEVERAGE_ENGINE_ADDRESS=${{ secrets.LEVERAGE_ENGINE_ADDRESS }} >> .env
          echo NEW_EVENTS_QUEUE_URL=${{ secrets.NEW_EVENTS_QUEUE_URL }} >> .env
          echo S3_BUCKET=${{ secrets.S3_BUCKET }} >> .env
          echo S3_KEY=${{ secrets.S3_KEY }} >> .env
          echo ALCHEMY_API_URL=${{ secrets.ALCHEMY_API_URL }} >> .env
          echo INFURA_API_URL=${{ secrets.INFURA_API_URL }} >> .env
          echo EVENTS_FETCH_PAGE_SIZE=${{ secrets.EVENTS_FETCH_PAGE_SIZE }} >> .env

      - name: Zip the code
        run: zip -r lambda.zip dist/* node_modules/ package.json .env

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: wbtc_events_fetcher
          zip_file: lambda.zip
