name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create .env file
        run: |
          echo LEVERAGE_ENGINE_ADDRESS=${{ secrets.LEVERAGE_ENGINE_ADDRESS }} >> .env
          echo NEW_EVENTS_QUEUE_URL=${{ secrets.NEW_EVENTS_QUEUE_URL }} >> .env
          echo S3_BUCKET=${{ secrets.S3_BUCKET }} >> .env
          echo S3_KEY=${{ secrets.S3_KEY }} >> .env
          echo ALCHEMY_API_URL=${{ secrets.ALCHEMY_API_URL }} >> .env
          echo INFURA_API_URL=${{ secrets.INFURA_API_URL }} >> .env
          echo EVENTS_FETCH_PAGE_SIZE=${{ secrets.EVENTS_FETCH_PAGE_SIZE }} >> .env

      - name: Zip the code
        run: zip -r lambda.zip dist/* node_modules/ package.json .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create or Update Lambda function
        run: |
          if aws lambda get-function --function-name your_lambda_function_name ; then
            echo "Function exists, updating."
            aws lambda update-function-code --function-name your_lambda_function_name --zip-file fileb://lambda.zip
          else
            echo "Function does not exist, creating."
            aws lambda create-function --function-name your_lambda_function_name \
                                        --zip-file fileb://lambda.zip \
                                        --handler your_handler \
                                        --runtime nodejs14.x \
                                        --role arn:aws:iam::your_iam_role_arn
          fi
