name: Test

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
  API_DEVOPS_EVENT_CATCHER: ${{ vars.API_DEVOPS_EVENT_CATCHER }}
  DEVOPS_EVENTS_SECRET_TOKEN: ${{ secrets.DEVOPS_EVENTS_SECRET_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Lint Code
        run: npx eslint src/**/*.ts --ext .js,.jsx,.ts,.tsx --ignore-pattern /devops/

      - name: Run npm Tests and Measure Time
        run: |
          START_TIME=$SECONDS
          npm test
          DURATION=$((SECONDS - START_TIME))
          echo "DURATION=$DURATION" >> $GITHUB_ENV

      - name: Check for changes in src/
        id: check_changes
        run: |
          echo "::set-output name=src_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/' && echo 'true' || echo 'false')"

      - name: SonarCloud Scan
        if: steps.check_changes.outputs.src_changed == 'true'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: 'Report DevOps Metrics'
        run: |
          echo "Time taken to run the script: ${{ env.DURATION }} seconds"

          npm install axios dotenv
          node devops/metrics/src/cicd_script/report_devops_event.js ${{ github.repository }} test_run '{"pass": "true", "time": "${{ env.DURATION }}" ,"coverage": {"functions": "NA", stryker_functions: "NA"}}'
