name: Test

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run npm Tests and Measure Time
        run: |
          START_TIME=$SECONDS
          npm test
          DURATION=$((SECONDS - START_TIME))
          echo "DURATION=$DURATION" >> $GITHUB_ENV

      - name: 'Report DevOps Metrics'
        run: |
          echo "Time taken to run the script: ${{ env.DURATION }} seconds"

          npm install axios dotenv
          node devops/metrics/src/cicd_script/report_devops_event.js ${{ github.repository }} "test_pass" '{"duration": ${{ env.DURATION }}}'
